// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import ChatroomController from "./chatroom_controller"
import MessageFormController from "./message_form_controller"
import ChatroomChannelController from "./chatroom_channel_controller"


application.register("hello", HelloController)
application.register("chatroom", ChatroomController)
application.register("message-form", MessageFormController)
application.register("chatroom-channel", ChatroomChannelController)